sparse: Fix build with 20.05 DPDK tracepoints.
When building against 20.05-rc1 which introduced a tracing framework,
mempool header now triggers an error with sparse.

.../dpdk-dir/build/include/rte_mempool_trace_fp.h:96:1:
 error: undefined identifier '__atomic_load_n'
.../dpdk-dir/build/include/rte_mempool_trace_fp.h:57:1:
 error: undefined identifier '__atomic_load_n'
.../dpdk-dir/build/include/rte_mempool_trace_fp.h:47:1:
 error: undefined identifier '__atomic_load_n'
.../dpdk-dir/build/include/rte_mempool_trace_fp.h:38:1:
 error: undefined identifier '__atomic_load_n'
.../dpdk-dir/build/include/rte_mempool_trace_fp.h:38:1:
 error: not a function <noident>
.../dpdk-dir/build/include/rte_mempool_trace_fp.h:38:1:
 error: undefined identifier '__ATOMIC_ACQUIRE'
.../dpdk-dir/build/include/rte_mempool_trace_fp.h:96:1:
 error: not a function <noident>

Wrap around the gcc atomic builtins used in one of the tracing framework
helper.

Signed-off-by: David Marchand <david.marchand@redhat.com>
Signed-off-by: 0-day Robot <robot@bytheb.org>