netdev-vport: Fix compilation warning
port is declared as uint16 so use %hu specifier instead of %d.

lib/netdev-vport.c:460:44: error: '%s' directive output may be truncated writing up to 4 bytes into a region of size between 1 and 10 [-Werror=format-truncation=]
      snprintf(namebuf, bufsize, "dst_port_%d%s",
                                           ^~
Fixes: 189de33f02b2 ("netdev-vport: reject concomitant incompatible tunnels")
Signed-off-by: Roi Dayan <roid@nvidia.com>
Reviewed-by: Eli Britstein <elibr@nvidia.com>
Signed-off-by: 0-day Robot <robot@bytheb.org>