ipf: Fix locking for lists and a deadlock with the clean thread.
In a few places the list sizes are checked without holding the lock.
While this probably speeds up the processing a bit, it's technically
incorrect as the access is not atomic.  Caught by thread-safety
analyzer of clang 21, as it now properly supports GUARDED annotations
on structure fields:

  lib/ipf.c:1117:33:
    error: reading the value pointed to by 'frag_exp_list' requires
    holding any mutex [-Werror,-Wthread-safety-analysis]
   1117 |     if (ovs_list_is_empty(&ipf->frag_exp_list)) {
        |                                 ^
  lib/ipf.c:1154:33:
    error: reading the value pointed to by 'reassembled_pkt_list'
    requires holding any mutex [-Werror,-Wthread-safety-analysis]
   1154 |     if (ovs_list_is_empty(&ipf->reassembled_pkt_list)) {
        |                                 ^

There is also a potential deadlock between the thread destroying the
ipf and the clean thread as they are using the latch and the ipf lock
in the opposite order.  The latch itself is thread-safe, so we should
not be holding the lock while setting it and waiting for the clean
thread that may be waiting for the lock.

Fixes: 4ea96698f667 ("Userspace datapath: Add fragmentation handling.")
Signed-off-by: Ilya Maximets <i.maximets@ovn.org>
Signed-off-by: 0-day Robot <robot@bytheb.org>