netdev-linux: Fix using uninitialized current_speed.
Used Ubuntu with gcc (Ubuntu 11.2.0-19ubuntu1) 11.2.0
lib/netdev-linux.c:4985:54: error: ‘current_speed’ may be used uninitialized in this function [-Werror=maybe-uninitialized]

Fixes: b8f8fad86435 ("netdev-linux: Use speed as max rate in tc classes.")
Signed-off-by: Roi Dayan <roid@nvidia.com>
Signed-off-by: 0-day Robot <robot@bytheb.org>