netdev-linux: Fix ethtool_cmd is partly outside array bounds.
Used Ubuntu with gcc (Ubuntu 11.2.0-19ubuntu1) 11.2.0

lib/netdev-linux.c: In function ‘netdev_linux_construct’:
lib/netdev-linux.c:7003:15: error: array subscript ‘struct ethtool_cmd[0]’ is partly outside array bounds of ‘union <anonymous>[1]’ [-Werror=array-bounds]
 7003 |     ecmd->cmd = cmd;
      |     ~~~~~~~~~~^~~~~
lib/netdev-linux.c:2411:7: note: while referencing ‘sset_info’
 2411 |     } sset_info;
      |       ^~~~~~~~~

Fixes: 6c59c195266c ("netdev-linux: Use ethtool to detect offload support.")
Signed-off-by: Roi Dayan <roid@nvidia.com>
Signed-off-by: 0-day Robot <robot@bytheb.org>