build: Fix build with Sparse for rte_mbuf.h.
Introduction of C11 atomic instructions in rte_mbuf.h causes the build
to fail with Sparse reporting following errors.

error: undefined identifier '__atomic_add_fetch'
error: undefined identifier '__atomic_store_n'

This patch udpates the Sprase headers for rte_mbuf.h.

Tested-at: https://travis-ci.org/github/Sunil-Pai-G/ovs-copy/builds/723223426
Signed-off-by: Sunil Pai G <sunil.pai.g@intel.com>
Signed-off-by: 0-day Robot <robot@bytheb.org>