Fix compilation error on Fedora 34 with GCC 11
With newest version of GCC, OVS fails to compile due to false-positive
overread detection in hash-related functions. Those function declares
"const uint32_t p[]" as argument and it throws off the compiler into
thinking that it reads from memory region of size 0.

To fix that behavior, a change in argument declaration needs to be made:
instead of using "[]" notation for a pointer, simply use "*".

The reported error in question:

lib/conntrack.c: In function ‘conn_key_hash’:
lib/conntrack.c:2154:12: error: ‘hash_words’ reading 4 bytes from a region of size 0 [-
Werror=stringop-overread]
 2154 |     return hash_words((uint32_t *) (&key->dst + 1),
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 2155 |                       (uint32_t *) (key + 1) - (uint32_t *) (&key->dst + 1),
      |                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 2156 |                       hash);
      |                       ~~~~~
lib/conntrack.c:2154:12: note: referencing argument 1 of type ‘const uint32_t *’ {aka ‘const
unsigned int *’}
In file included from lib/packets.h:31,
                 from lib/ct-dpif.h:21,
                 from lib/conntrack.h:23,
                 from lib/conntrack.c:26:
lib/hash.h:294:1: note: in a call to function ‘hash_words’
  294 | hash_words(const uint32_t p[], size_t n_words, uint32_t basis)
      | ^~~~~~~~~~

Signed-off-by: Guzowski Adrian <adrian.guzowski@exatel.pl>
Signed-off-by: 0-day Robot <robot@bytheb.org>