ovs-atomic: Rename memory_order -> ovs_memory_order
DPDK commit [1] uses function variables named "memory_order".
Compilation fails with:
error: declaration of 'memory_order' shadows a global declaration
[-Werror=shadow]
 rte_atomic_thread_fence(int memory_order)
Rename enum memory_order to ovs_memory_order to avoid that conflict.

[1] 672a15056380 ("eal: add wrapper for C11 atomic thread fence")

Signed-off-by: Eli Britstein <elibr@nvidia.com>
Signed-off-by: 0-day Robot <robot@bytheb.org>