tests/mfex: Rertain support for cryptography pre-v37.
Prior to v37.0.0, CryptographyDeprecationWarning could not be imported
from __init__.py resulting in:

Traceback (most recent call last):
  File "mfex_fuzzy.py", line 9, in <module>
    category=cryptography.CryptographyDeprecationWarning,
AttributeError: module 'cryptography' has no attribute
    'CryptographyDeprecationWarning'

This import was only added to __init__ to deprecate python3.6. Importing
the exception from cryptography.utils is the compatible option.

Signed-off-by: Mike Pattrick <mkp@redhat.com>
Signed-off-by: 0-day Robot <robot@bytheb.org>