datapath-linux: Fix kmod build with recent CentOS Stream kernels
With kernel 4.18.0-477.x.y there was a compilation error:

/builddir/build/BUILD/openvswitch-2.17.3/_4.18.0-477.10.1.el8_8.x86_64/../datapath/linux/compat/include/linux/mm.h:13:21: error: redefinition of 'kvmalloc'
 static inline void *kvmalloc(size_t size, gfp_t flags)
                     ^~~~~~~~
In file included from ./include/linux/crypto.h:24,
                 from ./include/crypto/hash.h:16,
                 from ./include/linux/uio.h:16,
                 from ./include/linux/socket.h:8,
                 from ./include/linux/skbuff.h:23,
                 from /builddir/build/BUILD/openvswitch-2.17.3/_4.18.0-477.10.1.el8_8.x86_64/../datapath/linux/compat/include/linux/skbuff.h:17,
                 from /builddir/build/BUILD/openvswitch-2.17.3/_4.18.0-477.10.1.el8_8.x86_64/datapath/linux/actions.c:21:
./include/linux/slab.h:740:21: note: previous definition of 'kvmalloc' was here

This was introduced by upstream kernel commit [0].
This patch fixes this error adding a new path to searched functions to lookup.

0: https://lore.kernel.org/all/20211105203507.gvGl5bZmw%25akpm@linux-foundation.org/

Signed-off-by: Vladislav Odintsov <odivlad@gmail.com>
Signed-off-by: 0-day Robot <robot@bytheb.org>