Revert "python: Replace deprecated License with License-Expression (PEP 639)."
This reverts commit 7330836535b52ad772a7878761e82226ce4d5706.

The 'License-Expression' is not a classifier, so it must not be in
the list of classifiers.  Otherwise PyPI rejects the package:

  HTTPError: 400 Bad Request

  The server could not comply with the request since it is either
  malformed or otherwise incorrect.

  400 'License-Expression :: Apache 2.0' is not a valid classifier.
  See https://packaging.python.org/specifications/core-metadata for
  more information.

So, the commit is clearly wrong.  The list of valid classifiers
can be seen here: https://pypi.org/classifiers/

We probably shouldn't list the classifier at all and change the
'license' field instead.  But that's a thing to explore later.
For now, just revert the change to the legacy working state.

Fixes: 7330836535b5 ("python: Replace deprecated License with License-Expression (PEP 639).")
Signed-off-by: Ilya Maximets <i.maximets@ovn.org>
Signed-off-by: 0-day Robot <robot@bytheb.org>